server:
  port: 8081
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

canal.conf:
  mode: kafka #rocketMQ rabbitMQ
  flatMessage: true
  zookeeperHosts:
  syncBatchSize: 1000
  retries: 10
  timeout:
  accessKey:
  secretKey:
  consumerProperties:
    # kafka consumer
    kafka.bootstrap.servers: 192.168.101.152:9092
    kafka.enable.auto.commit: false
    kafka.auto.commit.interval.ms: 1000
    kafka.auto.offset.reset: earliest
    kafka.request.timeout.ms: 40000
    kafka.session.timeout.ms: 30000
    kafka.isolation.level: read_committed
    kafka.max.poll.records: 1000

  srcDataSources:
    #    defaultDS:
    #      url: jdbc:mysql://rm-bp1yjb2rh8249f1ft90130.mysql.rds.aliyuncs.com:3306/spider?useUnicode=true
    #      username: dev
    #      password: dev123456
    postDS:
      url: jdbc:mysql://rm-bp1yjb2rh8249f1ft90130.mysql.rds.aliyuncs.com:3306/posting?useUnicode=true
      username: dev
      password: dev123456
  #    dwDS:
  #      url: jdbc:mysql://rm-bp1yjb2rh8249f1ft90130.mysql.rds.aliyuncs.com:3306/dw_service?useUnicode=true
  #      username: dev
  #      password: dev123456
  #    courseDS:
  #      url: jdbc:mysql://rm-bp1yjb2rh8249f1ft90130.mysql.rds.aliyuncs.com:3306/course?useUnicode=true
  #      username: dev
  #      password: dev123456
  #    merchantDS:
  #      url: jdbc:mysql://rm-bp1yjb2rh8249f1ft90130.mysql.rds.aliyuncs.com:3306/merchant?useUnicode=true
  #      username: dev
  #      password: dev123456
  #    schoolDS:
  #      url: jdbc:mysql://rm-bp1yjb2rh8249f1ft90130.mysql.rds.aliyuncs.com:3306/school?useUnicode=true
  #      username: dev
  #      password: dev123456
  #    commonDS:
  #      url: jdbc:mysql://rm-bp1yjb2rh8249f1ft90130.mysql.rds.aliyuncs.com:3306/common?useUnicode=true
  #      username: dev
  #      password: dev123456

  canalAdapters:
    - instance: posting_post # canal instance Name or mq topic name
      groups:
        #        - groupId: canal-adapter-be
        #          outerAdapters:
        #            - name: logger
        #            - name: es7
        #              hosts: es-cn-nif1u0p9m000ao3fn.elasticsearch.aliyuncs.com:9200 # 127.0.0.1:9200 for rest mode
        #              properties:
        #                mode: rest
        #                security.auth: elastic:Dev123456+ #  only used for rest mode
        #                cluster.name: elasticsearch
        - groupId: canal-adapter-ba
          outerAdapters:
            - name: logger
            - name: redis
              hosts: r-bp1lv6hmsmbxcmtahn.redis.rds.aliyuncs.com:6379
              properties:
                cluster: false
                password: Dev123456

#    - instance: posting_topic # canal instance Name or mq topic name
#      groups:
#        - groupId: canal-adapter-be
#          outerAdapters:
#            - name: logger
#            - name: es7
#              hosts: es-cn-nif1u0p9m000ao3fn.elasticsearch.aliyuncs.com:9200 # 127.0.0.1:9200 for rest mode
#              properties:
#                mode: rest
#                security.auth: elastic:Dev123456+ #  only used for rest mode
#                cluster.name: elasticsearch
#    - instance: course_course # canal instance Name or mq topic name
#      groups:
#        - groupId: canal-adapter-be
#          outerAdapters:
#            - name: logger
#            - name: es7
#              hosts: es-cn-nif1u0p9m000ao3fn.elasticsearch.aliyuncs.com:9200 # 127.0.0.1:9200 for rest mode
#              properties:
#                mode: rest
#                security.auth: elastic:Dev123456+ #  only used for rest mode
#                cluster.name: elasticsearch
#    - instance: course_course_allocation_record # canal instance Name or mq topic name
#      groups:
#        - groupId: canal-adapter-be
#          outerAdapters:
#            - name: logger
#            - name: es7
#              hosts: es-cn-nif1u0p9m000ao3fn.elasticsearch.aliyuncs.com:9200 # 127.0.0.1:9200 for rest mode
#              properties:
#                mode: rest
#                security.auth: elastic:Dev123456+ #  only used for rest mode
#                cluster.name: elasticsearch
#    - instance: merchant_merchant # canal instance Name or mq topic name
#      groups:
#        - groupId: canal-adapter-be
#          outerAdapters:
#            - name: logger
#            - name: es7
#              hosts: es-cn-nif1u0p9m000ao3fn.elasticsearch.aliyuncs.com:9200 # 127.0.0.1:9200 for rest mode
#              properties:
#                mode: rest
#                security.auth: elastic:Dev123456+ #  only used for rest mode
#                cluster.name: elasticsearch
#    - instance: merchant_teacher # canal instance Name or mq topic name
#      groups:
#        - groupId: canal-adapter-be
#          outerAdapters:
#            - name: logger
#            - name: es7
#              hosts: es-cn-nif1u0p9m000ao3fn.elasticsearch.aliyuncs.com:9200 # 127.0.0.1:9200 for rest mode
#              properties:
#                mode: rest
#                security.auth: elastic:Dev123456+ #  only used for rest mode
#                cluster.name: elasticsearch
#    - instance: merchant_network # canal instance Name or mq topic name
#      groups:
#        - groupId: canal-adapter-be
#          outerAdapters:
#            - name: logger
#            - name: es7
#              hosts: es-cn-nif1u0p9m000ao3fn.elasticsearch.aliyuncs.com:9200 # 127.0.0.1:9200 for rest mode
#              properties:
#                mode: rest
#                security.auth: elastic:Dev123456+ #  only used for rest mode
#                cluster.name: elasticsearch
#    - instance: merchant_bd_merchant # canal instance Name or mq topic name
#      groups:
#        - groupId: canal-adapter-be
#          outerAdapters:
#            - name: logger
#            - name: es7
#              hosts: es-cn-nif1u0p9m000ao3fn.elasticsearch.aliyuncs.com:9200 # 127.0.0.1:9200 for rest mode
#              properties:
#                mode: rest
#                security.auth: elastic:Dev123456+ #  only used for rest mode
#                cluster.name: elasticsearch
#    - instance: merchant_teacher_recruit # canal instance Name or mq topic name
#      groups:
#        - groupId: canal-adapter-be
#          outerAdapters:
#            - name: logger
#            - name: es7
#              hosts: es-cn-nif1u0p9m000ao3fn.elasticsearch.aliyuncs.com:9200 # 127.0.0.1:9200 for rest mode
#              properties:
#                mode: rest
#                security.auth: elastic:Dev123456+ #  only used for rest mode
#                cluster.name: elasticsearch
#    - instance: school_college_student_statistics # canal instance Name or mq topic name
#      groups:
#        - groupId: canal-adapter-be
#          outerAdapters:
#            - name: logger
#            - name: es7
#              hosts: es-cn-nif1u0p9m000ao3fn.elasticsearch.aliyuncs.com:9200 # 127.0.0.1:9200 for rest mode
#              properties:
#                mode: rest
#                security.auth: elastic:Dev123456+ #  only used for rest mode
#                cluster.name: elasticsearch
#    - instance: common_checking_lesson_teacher # canal instance Name or mq topic name
#      groups:
#        - groupId: canal-adapter-be
#          outerAdapters:
#            - name: logger
#            - name: es7
#              hosts: es-cn-nif1u0p9m000ao3fn.elasticsearch.aliyuncs.com:9200 # 127.0.0.1:9200 for rest mode
#              properties:
#                mode: rest
#                security.auth: elastic:Dev123456+ #  only used for rest mode
#                cluster.name: elasticsearch